
INSERT INTO AUTHORITY (ID, NAME) VALUES (1, 'ROLE_USER');
INSERT INTO AUTHORITY (ID, NAME) VALUES (2, 'ROLE_ADMIN');

INSERT INTO USER_ENTITY (ID, EMAIL, ENABLED, FIRSTNAME, LAST_PASSWORD_RESET_DATE, LASTNAME, PASSWORD, PROFILE_PIC, USERNAME) VALUES(1, 'odubinskiy@ukr.net',	TRUE , 'Oleg',	CURRENT_TIMESTAMP ,	'Dubinskiy',	'$2a$10$xQv4VZtE07sGbGkRKTEnIOAUSqtlpd2BJefq7DfDvuLS8HVCYrdFO',	'0lejk4'	,'0lejk4');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 2);